### ISSUE TITLE
Various Oreo issues

### ISSUE THREAD

**Issue by Mwyann** [meefik/linuxdeploy#1012]
I'm using a Samsung S7E on Oreo (Samsung firmware).

- The notification icon doesn't show up, thus Linux Deploy can be stopped by the OS.
- The auto startup doesn't work.
- The network trigger doesn't work.

Some selected logcat that may be useful?

10-04 22:57:42.833  3752  3787 D PackageManager: getComponentMetadataForIconTray : ru.meefik.linuxdeploy.MainActivity does not exist in mServices
10-04 22:57:42.833  3752  3787 D PackageManager: getComponentMetadataForIconTray : ru.meefik.linuxdeploy.MainActivity does not exist in mProviders
10-04 22:57:42.833  3752  3787 D PackageManager: getComponentMetadataForIconTray : ru.meefik.linuxdeploy.MainActivity does not exist in mReceivers
10-04 22:57:42.833  4369  4389 D ApplicationPackageManager: updateItemMetaDataForFixedIconScale: package: ru.meefik.linuxdeploy
10-04 22:57:42.833  3752  3787 D PackageManager: getSelectedMetaData : packageName(ru.meefik.linuxdeploy) or Metadata strings {[Ljava.lang.String;@baa2598}
10-04 22:57:42.834  4369  4389 I ApplicationPackageManager: load=ru.meefik.linuxdeploy, bg=144-144, dr=164-164, forDefault=true, density=0
10-04 22:57:42.834  4352  4352 D SamsungAnalytics111040: cf feature is supported
10-04 22:57:42.834  4369  4389 E ApplicationPackageManager: checkSettingsForIconTray value : 0
10-04 22:57:42.838  4369  4389 I ApplicationPackageManager: scaled rate=0.94, size=164, alpha=11, hold=102
10-04 22:57:42.838  4369  4389 I ApplicationPackageManager: load=ru.meefik.linuxdeploy-scale, bg=164-164, dr=164-164

**Comment by fafriat** [comment]
My pull request should fix the auto startup and possibly the network trigger bug.
#1041 

**References:** 
[stackoverflow](https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten)

Using the solution:

> The best way is to use JobIntentService which uses the new JobScheduler for Oreo or the old services if not available.

**Comment by meefik** [comment]
@fafriat thanks for your PR! I check it and include in the next release.

**Comment by Mwyann** [comment]
@fafriat Thanks for the fix :) I tried building and installing the latest commit, but I can't test it, I get an error when trying to update the environment, so I cannot start the container, and the icon still isn't showing in the status bar. But again, maybe I'm doing something wrong :) (I changed the app id to be able to install another instance)

**Comment by fafriat** [comment]
@Mwyann You're welcome. You need to clone also linuxdeploy-cli, it contains the environment.
You can clone it directly inside assets/env or use a symlink.

**Comment by Mwyann** [comment]
@fafriat Thanks, it works better now :) Unfortunately, none of the issues seems to have been fixed yet. No icon, no network trigger (a network change doesn't run the network update script) and no autostart :( But I'd be glad to help somehow.

**Comment by fafriat** [comment]
@Mwyann In my case the autostart is fixed. Be sure to uninstall the current version before installing the compiled one. Also in my case, I signed the apk, maybe that is necessary.
Is possible to run `logcat -d > log.txt `as root and to try to find an error in the logs when the android restarted ?

**Comment by Iscle** [comment]
The notification has been fixed with my commits, however I think the app is still not available in the Play Store. You can manually build it by cloning this repository.
