### ISSUE TITLE
Checking Mount Points ... Fail

### ISSUE THREAD

**Issue by Jacapo** [meefik/linuxdeploy#191]
Currently I am getting the following results. I have SuperSU and busybox installed.

Updating cofiguration file ... done
>>> begin: install
chcking mount points ... fail
press STOP and repeat attemt.
<<< end: install

I have been trying to figure out why and how to fix this. I haven't been able to find similar posts. I do know the mmcblk0p6 file is giving me a permission denied, but I have no idea why root access isn't allowing me to make a copy of that file.

**Comment by meefik** [comment]
Press STOP button and repeat installation.

**Comment by Jacapo** [comment]
Lol.  have done so. It fails every time.

On Sun, Feb 8, 2015 at 1:01 PM, Anton Skshidlevsky <notifications@github.com

**Comment by meefik** [comment]
Put here full log in debug mode.

**Comment by choco7ice** [comment]
I have the same problem. How do I see the log in debug mode?
Thx

**Comment by t2ll1x** [comment]
I have the same exact problem.
I have tried everything.

let me do an adb logcat and ill get back to you with the info

**Comment by choco7ice** [comment]
I have fixed this problem and successfully run kali linux on my phone. 
The problem is I was using a ROM that does not support loop devices.
I flashed a ROM called AOSP and then everything works fine.

**Comment by dlstjd** [comment]
[18:25:52] Updating configuration file ... done
[18:25:52] /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy: line 1655: uname: Permission denied
[18:25:52] >>> begin: install 
[18:25:52] Checking mount points ... /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy: line 1714: grep: Permission denied
[18:25:52] sh: bad number
[18:25:52] fail 
[18:25:52] Press STOP and repeat attempt. 
[18:25:52] <<< end: install

I get this problem,  how can I fix It?

**Comment by t2ll1x** [comment]
I knew it had to be the bootloop, on my galaxy note 3 there are no roms I
know of that have the kernel that supports bootloop. I've already looked :(

**Comment by ephemeral15** [comment]
This my device status:


[14:07:38] >>> begin: status 
[14:07:38] Linux Deploy version: 1.5.0-134 
[14:07:39] Device: CherryMobile Ultra 
[14:07:39] Android: 4.4.2 
[14:07:39] Architecture: armv7l 
[14:07:39] Kernel: 3.4.0-g498d9a6 
[14:07:39] Memory: 867680 KB 
[14:07:39] Swap: 0 KB 
[14:07:39] SELinux: yes 
[14:07:39] no 
[14:07:39] Loop devices: yes 
[14:07:39] Support binfmt_misc: no 
[14:07:39] Supported FS: ext2 ext3 ext4 fuseblk vfat  
[14:07:39] Mounted system: unknown 
[14:07:39] Running services:  
[14:07:39] * SSH: no 
[14:07:39] * VNC: no 
[14:07:39] Mounted parts on Linux:  
[14:07:39]  ...not mounted anything 
[14:07:39] Available mount points:  
[14:07:39] * /system: 0.3/1.0 GB (ext4) 
[14:07:39] * /data: 3.0/5.9 GB (ext4) 
[14:07:39] * /cache: 0.1/0.1 GB (ext4) 
[14:07:39] * /persist: 0.0/0.0 GB (ext4) 
[14:07:39] * /firmware: 0.0/0.1 GB (vfat) 
[14:07:39] * /storage/usbotg: 0.0/0.0 GB (fuse) 
[14:07:39] * /storage/sdcard1: 7.4/7.4 GB (fuse) 
[14:07:39] * /storage/uicc0: 0.0/0.0 GB (fuse) 
[14:07:39] * /mnt/shell/emulated: 3.0/5.9 GB (fuse) 
[14:07:39] * /storage/emulated/legacy: 3.0/5.9 GB (fuse) 
[14:07:39] * /mnt/media_rw/sdcard1: 7.4/7.4 GB (vfat) 
[14:07:39] * /storage/emulated/0: 3.0/5.9 GB (fuse) 
[14:07:39] * /storage/emulated/0/Android/obb: 3.0/5.9 GB (fuse) 
[14:07:39] * /storage/emulated/legacy: 3.0/5.9 GB (fuse) 
[14:07:39] * /storage/emulated/legacy/Android/obb: 3.0/5.9 GB (fuse) 
[14:07:39] Available partitions:  
[14:07:45] * /dev/block/mmcblk1p1: 7944 MB (Win95 FAT32) 
[14:07:45] <<< end: status



And this is my error:

[14:09:23] Updating configuration file ... done
[14:09:24] >>> begin: install 
[14:09:24] Checking mount points ... done 
[14:09:24] fail 
[14:09:24] Press STOP and repeat attempt. 
[14:09:24] <<< end: install


Anyone encounter this? How to fix these? TIA

**Comment by belhsan** [comment]
choco7ice  please bro tell me how did u fix it i have longtime looking for sloution but still the same

**Comment by choco7ice** [comment]
You have to flash a ROM that supports Loop services.
The one I use is this:
http://aokp.co/devices
And there are youtube videos on installing AOKP:
https://www.youtube.com/results?search_query=install+aokp
